### ISSUE TITLE
Rider "forgets" where Godot executable is

### ISSUE THREAD

**Issue by hhyyrylainen** [JetBrains/godot-support#23]
So I've been testing if I want to use rider for Godot development, and I've noticed that this plugin requires a running instance of the Godot editor in order to debug my game (whereas the MonoDevelop plugin for Godot I tried, can run just fine with Godot closed, it has the option to configure the used godot executable). Additionally it seems that if I let things just sit for a while (I left it for something like 30) I get this error if I try to start debugging:
`Failed to determine path to Godot executable`
Going back to Godot's editor (which I have not closed), and running the game once from there, fixes this issue. After that I can then debug from rider just fine. Until I let things sit again for a while and I need to do this again. So far I only got that once, as I haven't had time to just wait around and see if it consistently happens or not.

I tried to look really hard if there is some option where I could configure the used Godot executable to get around this annoyance, but I didn't find anything.

Screenshot of issue:
![Kuvakaappaus - 2020-05-12 12-39-46](https://user-images.githubusercontent.com/3796411/81691648-d424a300-9465-11ea-9ebe-552b5264a0bb.png)
It's the same error I get if I don't have Godot open.

**Comment by van800** [comment]
This is already fixed but only with upcoming Godot 3.2.2 release.
With 3.2.1 Running Editor is a requirement.

**Comment by hhyyrylainen** [comment]
That's nice. I'll keep an eye out, then, for when 3.2.2 gets released.

**Comment by damarindra** [comment]
Compiling by myself, and still doesn't work for me. Is it because I'm using Rider for Unreal? The path is already there tho.
![image](https://user-images.githubusercontent.com/8519218/82416140-c5f90700-9aa3-11ea-9411-59f0f8391931.png)

**Comment by van800** [comment]
@damarindra is that path correct? What do you do and what happenes?

**Comment by damarindra** [comment]
yes, it is the right path. 
- Open godot from that path & open the solution with rider 
- Select debug and run for godot 
![image](https://user-images.githubusercontent.com/8519218/82456459-75eb6600-9ade-11ea-8c83-bf30d54a73c0.png)
- make sure the port is right 
![image](https://user-images.githubusercontent.com/8519218/82456572-9b786f80-9ade-11ea-9fad-832240d8c801.png)
![image](https://user-images.githubusercontent.com/8519218/82456625-afbc6c80-9ade-11ea-8a75-afffc58a356d.png)
- click the debug and run button
![image](https://user-images.githubusercontent.com/8519218/82456433-6a983a80-9ade-11ea-8c2b-865c34083704.png)

**Comment by van800** [comment]
@damarindra could you please write me at discord? I am '@van800#9412'. I can either debug it with you or write down instructions for debugging or compile build with more diagnostics.

**Comment by Sejsel** [comment]
This is working correctly for me on Windows with Godot 3.2.2 beta. The code assumes that your project data is in the default location of `%appdata%/Godot/projects`, did you perhaps change that location?
https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html#editor-data-paths

**Comment by Sejsel** [comment]
@damarindra Are you perhaps using the [self-contained mode](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html#self-contained-mode)? The Godot version distributed by Steam has this enabled by default.

**Comment by damarindra** [comment]
@Sejsel all correct. 
![image](https://user-images.githubusercontent.com/8519218/82520519-8f2bfb00-9b4e-11ea-85ee-09d7f7f05c96.png)

I don't know if this affect, but the port on rider always reset to 0 whenever reopen the rider.

**Comment by damarindra** [comment]
anyway, I just got the answer. So, my project was actually created with Godot 3.2.1 and without C#. I copied the project, open with the new godot with c-sharp support. the debug and run is just doesn't work. now I create a new project with godot c# version, it is now working fine.
