### ISSUE TITLE
Do not mark methods connected to signals as unused

### ISSUE THREAD

**Issue by XReaper95** [JetBrains/godot-support#90]
Currently, methods that are connected to a signal (through the editor) are marked as unused by Rider:

![Screenshot_2023-01-05_11-34-10](https://user-images.githubusercontent.com/31300566/210805326-7d98d720-2c3c-4d2c-b349-473940aedb99.png) (Example from Thrive)

It would be nice to add a feature to show the scene file where the connection is stored and mark it as referenced by Godot or something, like the Unity plugin does.

**Comment by van800** [comment]
I think for the Godot 4 this is solved with source generators on the Godot side.

**Comment by jking47** [comment]
I am still seeing this issue on my side, signal connected in the godot editor and I get the 'Unused Method' warning on it. Checking in the built in godot script editor doesn't throw this warning. I am using GDScript, Godot 4.3 and Rider 2024.2.7

![ShareX_ckpYB4Kf8q](https://github.com/user-attachments/assets/e95ab602-d76c-4a87-b1fb-62ebd2fb8be8)
![Godot_v4 3-stable_win64_aJvpn8tDEN](https://github.com/user-attachments/assets/5c70ae53-1e06-45e4-87af-8a5ed24a88ea)

**Comment by Arakade** [comment]
> EDIT: Actually after testing my error was from the 3rd party gdscript plugin, trying to avoid using that one so uninstalled, but I do have the above users issue with no method being seen as 'unused'. More minor issue for me

Think this is likely the issue https://gitlab.com/IceExplosive/gdscript/-/issues/172
Seems to say that _some_ scene usages are detected but some are not -- only works when ".tscn file has directly attached .gd script file" (implication: not when used in prefabs, IIUC).

**Comment by van800** [comment]
Close in favor of https://youtrack.jetbrains.com/issue/RIDER-140037/C-FindUsages-in-Scenes
